using DansBlog.Model.Entities;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace DansBlog.DataAccess
{
    public class BlogDataInitializer : DropCreateDatabaseAlways<BlogDbContext>
    {
        protected override void Seed(BlogDbContext context)
        {
            var posts = new List<Post>
                {
                    new Post{PublishDate = new DateTime(2011, 10, 7), Author = "Author 1", Title = "Title 1", Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vehicula in tellus at rutrum. Mauris lacinia lectus dui. Suspendisse non scelerisque enim. Nullam scelerisque porttitor lectus, eu congue est viverra a. Phasellus nec nulla vitae nisl mattis hendrerit vitae eget purus. In eget sodales sem, a blandit ipsum. Pellentesque congue quis felis sit amet pharetra. Vestibulum congue velit ante. Aenean mauris velit, hendrerit ut faucibus sed, molestie nec dui. Nam eu augue varius, rhoncus dolor non, iaculis felis. Proin vitae aliquam augue, a semper risus. Integer sodales tempus facilisis.", Categories = new List<Category>{new Category{Name = "Category One"}}, Comments = new List<Comment>{new Comment{Author = "Daniel Dutton", CreationTime = new DateTime(2013, 12, 01), Content = "Comment 1 Content", Email = "test@test.com"}}},
                    new Post{PublishDate = new DateTime(2011, 10, 18), Author = "Author 2", Title = "Title 2", Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vehicula in tellus at rutrum. Mauris lacinia lectus dui. Suspendisse non scelerisque enim. Nullam scelerisque porttitor lectus, eu congue est viverra a. Phasellus nec nulla vitae nisl mattis hendrerit vitae eget purus. In eget sodales sem, a blandit ipsum. Pellentesque congue quis felis sit amet pharetra. Vestibulum congue velit ante. Aenean mauris velit, hendrerit ut faucibus sed, molestie nec dui. Nam eu augue varius, rhoncus dolor non, iaculis felis. Proin vitae aliquam augue, a semper risus. Integer sodales tempus facilisis.", Categories = new List<Category>{new Category{Name = "Category Two"}}, Comments = new List<Comment>{new Comment{Author = "Daniel Dutton", CreationTime = new DateTime(2013, 12, 01), Content = "Comment 2 Content", Email = "test@test.com"}}},
                    new Post{PublishDate = new DateTime(2011, 10, 22), Author = "Author 3", Title = "Title 3", Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vehicula in tellus at rutrum. Mauris lacinia lectus dui. Suspendisse non scelerisque enim. Nullam scelerisque porttitor lectus, eu congue est viverra a. Phasellus nec nulla vitae nisl mattis hendrerit vitae eget purus. In eget sodales sem, a blandit ipsum. Pellentesque congue quis felis sit amet pharetra. Vestibulum congue velit ante. Aenean mauris velit, hendrerit ut faucibus sed, molestie nec dui. Nam eu augue varius, rhoncus dolor non, iaculis felis. Proin vitae aliquam augue, a semper risus. Integer sodales tempus facilisis.", Categories = new List<Category>{new Category{Name = "Category Three"}}, Comments = new List<Comment>{new Comment{Author = "Daniel Dutton", CreationTime = new DateTime(2013, 12, 01), Content = "Comment 3 Content", Email = "test@test.com"}}},
                    new Post{PublishDate = new DateTime(2012, 11, 14), Author = "Author 4", Title = "Title 4", Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vehicula in tellus at rutrum. Mauris lacinia lectus dui. Suspendisse non scelerisque enim. Nullam scelerisque porttitor lectus, eu congue est viverra a. Phasellus nec nulla vitae nisl mattis hendrerit vitae eget purus. In eget sodales sem, a blandit ipsum. Pellentesque congue quis felis sit amet pharetra. Vestibulum congue velit ante. Aenean mauris velit, hendrerit ut faucibus sed, molestie nec dui. Nam eu augue varius, rhoncus dolor non, iaculis felis. Proin vitae aliquam augue, a semper risus. Integer sodales tempus facilisis.", Categories = new List<Category>{new Category{Name = "Category Four"}}, Comments = new List<Comment>{new Comment{Author = "Daniel Dutton", CreationTime = new DateTime(2013, 12, 01), Content = "Comment 4 Content", Email = "test@test.com"}}},
                    new Post{PublishDate = new DateTime(2012, 11, 4), Author = "Author 5", Title = "Title 5", Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vehicula in tellus at rutrum. Mauris lacinia lectus dui. Suspendisse non scelerisque enim. Nullam scelerisque porttitor lectus, eu congue est viverra a. Phasellus nec nulla vitae nisl mattis hendrerit vitae eget purus. In eget sodales sem, a blandit ipsum. Pellentesque congue quis felis sit amet pharetra. Vestibulum congue velit ante. Aenean mauris velit, hendrerit ut faucibus sed, molestie nec dui. Nam eu augue varius, rhoncus dolor non, iaculis felis. Proin vitae aliquam augue, a semper risus. Integer sodales tempus facilisis.", Categories = new List<Category>{new Category{Name = "Category Five"}}, Comments = new List<Comment>{new Comment{Author = "Daniel Dutton", CreationTime = new DateTime(2013, 12, 01), Content = "Comment 5 Content", Email = "test@test.com"}}},
                    new Post{PublishDate = new DateTime(2012, 11, 3), Author = "Author 6", Title = "Title 6", Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vehicula in tellus at rutrum. Mauris lacinia lectus dui. Suspendisse non scelerisque enim. Nullam scelerisque porttitor lectus, eu congue est viverra a. Phasellus nec nulla vitae nisl mattis hendrerit vitae eget purus. In eget sodales sem, a blandit ipsum. Pellentesque congue quis felis sit amet pharetra. Vestibulum congue velit ante. Aenean mauris velit, hendrerit ut faucibus sed, molestie nec dui. Nam eu augue varius, rhoncus dolor non, iaculis felis. Proin vitae aliquam augue, a semper risus. Integer sodales tempus facilisis.", Categories = new List<Category>{new Category{Name = "Category Six"}}, Comments = new List<Comment>{new Comment{Author = "Daniel Dutton", CreationTime = new DateTime(2013, 12, 01), Content = "Comment 6 Content", Email = "test@test.com"}}},
                    new Post{PublishDate = new DateTime(2013, 12, 27), Author = "Author 7", Title = "Title 7", Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vehicula in tellus at rutrum. Mauris lacinia lectus dui. Suspendisse non scelerisque enim. Nullam scelerisque porttitor lectus, eu congue est viverra a. Phasellus nec nulla vitae nisl mattis hendrerit vitae eget purus. In eget sodales sem, a blandit ipsum. Pellentesque congue quis felis sit amet pharetra. Vestibulum congue velit ante. Aenean mauris velit, hendrerit ut faucibus sed, molestie nec dui. Nam eu augue varius, rhoncus dolor non, iaculis felis. Proin vitae aliquam augue, a semper risus. Integer sodales tempus facilisis.", Categories = new List<Category>{new Category{Name = "Category Seven"}}, Comments = new List<Comment>{new Comment{Author = "Daniel Dutton", CreationTime = new DateTime(2013, 12, 01), Content = "Comment 7 Content", Email = "test@test.com"}}},
                    new Post{PublishDate = new DateTime(2013, 12, 13), Author = "Author 8", Title = "Title 8", Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vehicula in tellus at rutrum. Mauris lacinia lectus dui. Suspendisse non scelerisque enim. Nullam scelerisque porttitor lectus, eu congue est viverra a. Phasellus nec nulla vitae nisl mattis hendrerit vitae eget purus. In eget sodales sem, a blandit ipsum. Pellentesque congue quis felis sit amet pharetra. Vestibulum congue velit ante. Aenean mauris velit, hendrerit ut faucibus sed, molestie nec dui. Nam eu augue varius, rhoncus dolor non, iaculis felis. Proin vitae aliquam augue, a semper risus. Integer sodales tempus facilisis.", Categories = new List<Category>{new Category{Name = "Category Eight"}}},
                    new Post{PublishDate = new DateTime(2013, 12, 2), Author = "Author 9", Title = "Title 9", Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vehicula in tellus at rutrum. Mauris lacinia lectus dui. Suspendisse non scelerisque enim. Nullam scelerisque porttitor lectus, eu congue est viverra a. Phasellus nec nulla vitae nisl mattis hendrerit vitae eget purus. In eget sodales sem, a blandit ipsum. Pellentesque congue quis felis sit amet pharetra. Vestibulum congue velit ante. Aenean mauris velit, hendrerit ut faucibus sed, molestie nec dui. Nam eu augue varius, rhoncus dolor non, iaculis felis. Proin vitae aliquam augue, a semper risus. Integer sodales tempus facilisis.", Categories = new List<Category>{new Category{Name = "Category Nine"}}},
                    new Post{PublishDate = new DateTime(2014, 1, 8), Author = "Author 10", Title = "Title 10", Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vehicula in tellus at rutrum. Mauris lacinia lectus dui. Suspendisse non scelerisque enim. Nullam scelerisque porttitor lectus, eu congue est viverra a. Phasellus nec nulla vitae nisl mattis hendrerit vitae eget purus. In eget sodales sem, a blandit ipsum. Pellentesque congue quis felis sit amet pharetra. Vestibulum congue velit ante. Aenean mauris velit, hendrerit ut faucibus sed, molestie nec dui. Nam eu augue varius, rhoncus dolor non, iaculis felis. Proin vitae aliquam augue, a semper risus. Integer sodales tempus facilisis.", Categories = new List<Category>{new Category{Name = "Category Ten"}}},
                };

            foreach (var post in posts)
                context.Posts.Add(post);

            base.Seed(context);
        }
    }
}
